### ISSUE TITLE
Support for emojis

### ISSUE THREAD

**Issue by Gabbalo** [PyFPDF/fpdf2#145]
Is there any chance to implement the support for emojis to the generator? There is a free font at google called [Noto](https://www.google.com/get/noto/help/emoji/) which might be used (not sure).
As emojis are used widely all over the web and some pages even accept them as password, it would be great, if this wonderful asset whould have the support for it, too, wouldn't it?

**Comment by Lucas-C** [comment]
Good question! Thanks for asking.
Some elements to answer:

* the [Zapf Dingbats](https://en.wikipedia.org/wiki/Zapf_Dingbats) is a builtin font in `fpdf2`,
so that is one way to display some signs & symbols using a font right now:
```python
pdf.set_font("ZapfDingbats")
```

* currently, `fpdf2` does not seem able to parse `NotoColorEmoji.ttf`:
```python
from fpdf import FPDF
pdf = FPDF()
pdf.add_font("NotoColorEmoji", fname="NotoColorEmoji.ttf", uni=True)
pdf.set_font("NotoColorEmoji")
pdf.add_page()
pdf.text(50, 50, "😃")
pdf.output("emoji.pdf")
```
Raises:
```
Traceback (most recent call last):
  File "./emoji.py", line 18, in <module>
    pdf.output("emoji.pdf")
  File "/opt/fpdf2/fpdf/fpdf.py", line 1850, in output
    self.close()
  File "/opt/fpdf2/fpdf/fpdf.py", line 499, in close
    self._enddoc()  # close document
  File "/opt/fpdf2/fpdf/fpdf.py", line 2540, in _enddoc
    self._putresources()  # trace_size is performed inside
  File "/opt/fpdf2/fpdf/fpdf.py", line 2435, in _putresources
    self._putfonts()
  File "/opt/fpdf2/fpdf/fpdf.py", line 2116, in _putfonts
    ttfontstream = ttf.makeSubset(font["ttffile"], subset)
  File "/opt/fpdf2/fpdf/ttfonts.py", line 498, in makeSubset
    self.getLOCA(indexToLocFormat, numGlyphs)
  File "/opt/fpdf2/fpdf/ttfonts.py", line 895, in getLOCA
    start = self.seek_table("loca")
  File "/opt/fpdf2/fpdf/ttfonts.py", line 128, in seek_table
    tpos = self.get_table_pos(tag)
  File "/opt/fpdf2/fpdf/ttfonts.py", line 115, in get_table_pos
    offset = self.tables[tag]["offset"]
KeyError: 'loca'
```
Seems like `TTFontFile.makeSubset("NotoColorEmoji.ttf", subset)` looks for a [loca](https://docs.microsoft.com/en-us/typography/opentype/spec/loca) table and does not find one.

I think that is because the Noto font is a CBDT/CBLC font, and we do not support them yet.

* I also tried another font providing support for emojis: [OpenSansEmoji](https://github.com/MorbZ/OpenSansEmoji).
This time `fpdf2` is able to parse it well, but the end result is not great:
[OpenSansEmoji-smiley.pdf](https://github.com/PyFPDF/fpdf2/files/6450828/OpenSansEmoji-smiley.pdf)

Of course, anyone is welcome to try to dig deeper on the subject,
and PRs are very welcome to improve `fpdf2` support of emoji fonts!

As [mentioned before](https://github.com/PyFPDF/fpdf2/issues/21#issuecomment-754872275) by @alexp1917, the other maintainer of `fpdf2`, we could consider using an external lib for font parsing & manipulation, in order to improve `fpdf2` support of fonts in terms of features & robustness.

**Comment by Lucas-C** [comment]
Implemented by @moe-25 as part of https://github.com/PyFPDF/fpdf2/pull/183

**Comment by Lucas-C** [comment]
This has just been released in fpdf2.4.3

**Comment by markusnordstrom** [comment]
Hi,

Using the same example code from the second post of this thread, I still get the same error and no emojis on version 2.4.3. The only change I see in this is the line number 895 changing to 909:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fpdf/ttfonts.py", line 909, in getLOCA
    start = self.seek_table("loca")
  File "/usr/local/lib/python3.7/site-packages/fpdf/ttfonts.py", line 128, in seek_table
    tpos = self.get_table_pos(tag)
  File "/usr/local/lib/python3.7/site-packages/fpdf/ttfonts.py", line 115, in get_table_pos
    offset = self.tables[tag]["offset"]
KeyError: 'loca'`

**Comment by Lucas-C** [comment]
CBDT/CBLC fonts are still not supported by fpdf2.

You can however use the DejaVuSans font:
```python
from fpdf import FPDF
pdf = FPDF()
pdf.add_font("DejaVuSans", fname="test/fonts/DejaVuSans.ttf", uni=True)
pdf.set_font("DejaVuSans")
pdf.add_page()
pdf.text(50, 50, "😃")
pdf.output("emoji.pdf")
```

**Comment by markusnordstrom** [comment]
Thanks for the reply! As DejaVuSans seems to have only the most basic emojis, I will have to look for another solution. Are there any plans to include CBDT/CBLC font support, or any issue I could follow meanwhile? Looking at the header, I don't think this issue is actually solved yet, but I'll leave it to you to consider whether it should be reopened.

Example code still creating just squares:

```
from fpdf import FPDF
pdf = FPDF()
pdf.add_font("DejaVuSans", fname="test/fonts/DejaVuSans.ttf", uni=True)
pdf.set_font("DejaVuSans")
pdf.add_page()
pdf.text(50, 50, "🐟🎧🌟")
pdf.output("emoji.pdf")
```

**Comment by Lucas-C** [comment]
I think I consider that fpdf2 now has some "basic" support for emojis (with some fonts),
which is why I closed this.

I'm totally OK if you want to open an issue about CBDT/CBLC font support,
if you have a need for them.
