### ISSUE TITLE
Cell borders, alignment and get_string_width

### ISSUE THREAD

**Issue by skwde** [PyFPDF/fpdf2#199]
How to account for width added by using border around a `cell`?
I guess the same applies when calculating the height.

Or asked differently how to get the actuall size of a cell?

The problem is related to the `w` variable in `cell` becaue it uses the width as actual string length, also when setting e.g. `border=1`.
Is there already a way to do it? 
If not, maybe  `cell` should use `w` as the actuall width of the cell when specifying a `border` value in `[1, L, R ]`; Analog when using `h`.

Following should visualize the issue
```python
import fpdf as FPDF
pdf = FPDF()
txt = "text"
txt_length = pdf.get_string_width(txt)
pdf.cell(txt=txt, border=1)
pdf.ln()
pdf.cell(w=txt_length, txt=txt, align='R', border=1)
```
![grafik](https://user-images.githubusercontent.com/26454702/128363247-99441129-942d-41a5-b691-325c92dd8d48.png)

**Comment by AubsUK** [comment]
I think you're referring to cell padding (internal margin).  It looks like the border is always there, but either coloured or not.  it also looks like it's c_margin (Cell Margin) that's responsible here.

- If you don't speficy a width, you're allowing the cell to expand to fit the text with a built-in cell margin (padding).
- If you specify a width, you are restricting the cell to that size.  You're setting it to right alight, so it inserts padding on both sides, but you only see the one on the right hand side because the text you're trying to output is too wide for the width+c_margin, it overhangs a little, by the amount in c_margin.

To correct this for your code, you could either set `pdf.c_margin = 0` or add whatever the current c_margin is to your width with `pdf.cell(w=txt_length + c_margin, txt=txt, align='R', border=1)` 

- Your original = centered with padding both sides
- Your original, width restricted, right aligned = overhanging
- My add the extra for the padding to the width = kinda looks left aligned, but right aligned with left padding [technically there is a left padding too, but that overhangs the cell]
- My set c_margin to zero = no margins either side

![image](https://user-images.githubusercontent.com/68870168/128776431-59c3a6dc-d8cc-4c07-b6bc-69b8082ae248.png)

Here's the code to generate the above image:
```
pdf = FPDF()
pdf.add_page()
pdf.set_font('helvetica', 'B', 16)
txt = "text"
txt_length = pdf.get_string_width(txt)
pdf.cell(txt=txt, border=1)
pdf.ln()
# Your original
pdf.cell(w=txt_length, txt=txt, align='R', border=1)
pdf.ln()
# Add c_margin to the width of the cell
pdf.cell(w=txt_length + pdf.c_margin, txt=txt, align='R', border=1)
pdf.c_margin = 0
pdf.ln()
# Set c_margin to zero
pdf.cell(w=txt_length, txt=txt, align='R', border=1)

pdf.output('test2.pdf', 'F')
```
.
.
This is where it comes from...

Extract from Line [331](https://github.com/PyFPDF/fpdf2/blob/19b1d29ca9058a5464c04d0fab2d920275975a4e/fpdf/fpdf.py#L331)
```
        self.c_margin = margin / 10.0  # Interior cell margin (1 mm)
```

Extract from Line [1646](https://github.com/PyFPDF/fpdf2/blob/19b1d29ca9058a5464c04d0fab2d920275975a4e/fpdf/fpdf.py#L1646) to Line [1652](https://github.com/PyFPDF/fpdf2/blob/19b1d29ca9058a5464c04d0fab2d920275975a4e/fpdf/fpdf.py#L1652)
```
        if txt:
            if align == "R":
                dx = w - self.c_margin - self.get_string_width(txt, True, markdown)
            elif align == "C":
                dx = (w - self.get_string_width(txt, True, markdown)) / 2
            else:
                dx = self.c_margin
```
.
.
 This page gives an example of setting the c_margin to zero...

https://github.com/roman-tolchenov/pdf/blob/master/fpdf_test.py

Extract from Line [42](https://github.com/roman-tolchenov/pdf/blob/ae35b21ecaac8bb847b812afc52dea6a5fe1c9dd/fpdf_test.py#L42) to Line [77](https://github.com/roman-tolchenov/pdf/blob/ae35b21ecaac8bb847b812afc52dea6a5fe1c9dd/fpdf_test.py#L77)

```
    def test_pdf_cell(self):
        pdf=FPDF()
        pdf.c_margin = 0.0
        pdf.add_font('symbol','','font/DejaVuSans.ttf',uni=True)
        pdf.add_page()
        f = 0.81
        font_name = 'times'
        
        text = 'small text'
        pdf.set_font(font_name,'',12)
        x,y = pdf.get_x(), pdf.get_y()
        w = pdf.get_string_width(text)
        h = pdf.font_size_pt / pdf.k
        pdf.cell(w, h, text)
        pdf.rect(x, y, w, h, '')
        pdf.line(x, y + f * h, x + w, y + f * h)
        
        text = 'Large text'
        pdf.set_font(font_name,'',24)
        x,y = pdf.get_x(), pdf.get_y()
        w = pdf.get_string_width(text)
        h = pdf.font_size_pt / pdf.k
        pdf.cell(w,h, text)
        pdf.rect(x, y, w, h, '')
        pdf.line(x, y + f * h, x + w, y + f * h)
        
        text = 'Larger text'
        pdf.set_font(font_name,'',48)
        x,y = pdf.get_x(), pdf.get_y()
        w = pdf.get_string_width(text)
        h = pdf.font_size_pt / pdf.k
        pdf.cell(w,h, text)
        pdf.rect(x, y, w, h, '')
        pdf.line(x, y + f * h, x + w, y + f * h)
```

**Comment by AubsUK** [comment]
Note on my last, if you want to change the c_margin, it would be worthwhile to capture the current value and then reset it back after:

```
temp_cmargin = pdf.c_margin
pdf.c_margin = 0
pdf.cell(w=txt_length, txt=txt, align='R', border=1)
pdf.c_margin = temp_cmargin
```

**Comment by Lucas-C** [comment]
Thanks for answering this in details @AubsUK ! 💖

Does that solve your issue @skwde ?

**Comment by Lucas-C** [comment]
@all-contributors please add @AubsUK for question

**Comment by skwde** [comment]
Sorry for my late reply.
@AubsUK & @Lucas-C yes, this exectly solves my questions. Thanks!
