### ISSUE TITLE
Background in Template not working

### ISSUE THREAD

**Issue by johann-su** [PyFPDF/fpdf2#203]
I am having trouble getting the background on boxes to work when using templates. 

There is an open issue in the original repo ([#151](https://github.com/reingart/pyfpdf/issues/151)) and a pull request ([#74](https://github.com/reingart/pyfpdf/pull/74)). 

An example for reproduction:
```Python
from fpdf import Template

elements = [
    # Paper markings
    { 'name': 'marking_1', 'type': 'B', 'x1': 5, 'y1': 105, 'x2': 10, 'y2': 105.5, 'font': None, 'size': 0.0, 'bold': 0, 'italic': 0, 'underline': 0, 'foreground': 0, 'background': '0x000000', 'align': 'I', 'text': None, 'priority': 1, },
    { 'name': 'marking_2', 'type': 'B', 'x1': 5, 'y1': 148.5, 'x2': 10, 'y2': 149, 'font': None, 'size': 0.0, 'bold': 0, 'italic': 0, 'underline': 0, 'foreground': 0, 'background': '0x000000', 'align': 'I', 'text': None, 'priority': 1, },
    { 'name': 'marking_3', 'type': 'B', 'x1': 5, 'y1': 210, 'x2': 10, 'y2': 210.5, 'font': None, 'size': 0.0, 'bold': 0, 'italic': 0, 'underline': 0, 'foreground': 0, 'background': '0x000000', 'align': 'I', 'text': None, 'priority': 1, },
]

# here we instantiate the template and define the HEADER
f = Template(format="A4", elements=elements,
             title="Sample Invoice")
f.add_page()

# and now we render the page
f.render("./template.pdf")
```

**Comment by alexp1917** [comment]
it would be good to add this and #205 in the same release. The fix for this issue must contain a test though.

I notice there are some code changes which i do not understand. the default value of background can stay as `65535` instead of `0xFFFFFF`. but [this bit][1], for instance:

```python
if pdf.text_color!=rgb(foreground):
  pdf.set_text_color(*rgb(foreground))
```

that avoids un-necessary pdf syntax from being added to the document, so i would try to keep that unless there's a good reason not to.

It seems like the critical places that we want to change the code (and create tests for) are: lines [140][2], [164][3], [167][4], [173][5], and lines 186-189 seem like they need review as well.

[1]: https://github.com/reingart/pyfpdf/pull/74/files#diff-832aa246d8865279dca20e45fca326ca2e04f8eab34980953dfad54575da9404L143
[2]: https://github.com/reingart/pyfpdf/pull/74/files#diff-832aa246d8865279dca20e45fca326ca2e04f8eab34980953dfad54575da9404R140
[3]: https://github.com/reingart/pyfpdf/pull/74/files#diff-832aa246d8865279dca20e45fca326ca2e04f8eab34980953dfad54575da9404R164
[4]: https://github.com/reingart/pyfpdf/pull/74/files#diff-832aa246d8865279dca20e45fca326ca2e04f8eab34980953dfad54575da9404R167
[5]: https://github.com/reingart/pyfpdf/pull/74/files#diff-832aa246d8865279dca20e45fca326ca2e04f8eab34980953dfad54575da9404R173

**Comment by Lucas-C** [comment]
I opened a PR to fix this: https://github.com/PyFPDF/fpdf2/pull/206

**Comment by Lucas-C** [comment]
This has just been released in fpdf2.4.3
