### ISSUE TITLE
Template.parse_csv() fails with "numeric" text field

### ISSUE THREAD

**Issue by gmischler** [PyFPDF/fpdf2#215]
When a csv file contains an entry of the following form,

`line0;T;20.0;13.0;190.0;13.0;times;10.0;0;0;0;0;65535;C;987654321;0;0`

where the contents of the text field look to Python like a number (here: "987654321"), then it will fail.
The source of the problem is in `util.try_to_type()`, which tries to "guess" the type of an entry based on the data found there.
The result, which has now been converted to a numeric value, will later understandably refuse to act like text string, causing an exception.

I remember reading "In the face of ambiguity, refuse the temptation to guess." somewhere... :wink:

Instead, the type conversion should be done depending on the position in the template line.
One of the simplest ways is probably to change the local keys attribute to a tuple of tuples, where the first item of each is the key and the second a conversion function (str.strip for the text entries, so the global stripping can be omitted).

**Comment by Lucas-C** [comment]
> I remember reading "In the face of ambiguity, refuse the temptation to guess." somewhere... 😉
> Instead, the type conversion should be done depending on the position in the template line.

Agreed!

A PR improving things would be very welcome 😉

**Comment by alexp1917** [comment]
> understandably

nope sorry, my understanding of types is either they get checked at compile time or i dont have to care. My lack of python intuition will likely keep causing issues, as this library is more popular now than it used to be, since @Lucas-C did such a good job of making the github look presentable. So the real long term solution, imo, is for someone who programs in python (more than I) to simply take my place.

anyways not sure what the best solution is, cause mine clearly did not cut it. If forcing the user to specify the types in the input is an option we could implement that (not sure I'd want to do that if i had a csv which i needed to generate a pdf out of). we could also do push the util call down the road closer to where the numeric value is needed, maybe even replacing the return with an exception "hey you needed a number here" or something.

**Comment by gmischler** [comment]
> 
> 
> > understandably

That was a joke, btw... :wink:

> nope sorry, my understanding of types is either they get checked at compile time or i dont have to care. 

Since we're talking about parsing **_user data_** from csv files here, compile time type checking in the usual sense is not the issue. The conversion (and implicit validity check) always has to happen at run time, but the decision about which item gets converted into which type **_must_** be hard-coded at compile time. 

> My lack of python intuition will likely keep causing issues, ...

The problem is not python specific. Such a guessing function would be problematic in any language (though under static typing it would be a lot less tempting to even try guessing).

> If forcing the user to specify the types in the input is an option we could implement that ...

Nope. Neither the library user nor the actual end user should be bothered with this.

> we could also do push the util call down the road closer to where the numeric value is needed, maybe even replacing the return with an exception "hey you needed a number here" or something.

The problem is not "you need a number", but that a _text field_ can get converted into a _numeric type_ incorrectly, based entirely on how the **_user data_** "looks like". This is essentially a denial-of-service attack triggered by certain forms of otherwise perfectly valid input data.

In the name of deterministic software behaviour, `util.try_to_type()` has to go away completely.

I'll see what I can do about a PR.

**Comment by gmischler** [comment]
Pull request #219 submitted.

**Comment by Lucas-C** [comment]
https://github.com/PyFPDF/fpdf2/pull/219 has been merged, closing this
