### ISSUE TITLE
Issue with the use of markdown and justified text (align="J")

### ISSUE THREAD

**Issue by pwt** [PyFPDF/fpdf2#327]
## Error details

Justified text (`align="J"`) doesn't render correctly when bold markdown is present. Please see the justified paragraph examples in the attached PDF [markdown_test.pdf](https://github.com/PyFPDF/fpdf2/files/7918489/markdown_test.pdf) when markdown is used.

Thanks in advance for taking a look at this. Let me know if any additional details/testing would be useful.

## Minimal Code

The following code was used to generate the attached PDF.

```Python
from fpdf import FPDF

test_paragraph_no_markdown = (
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, "
    "sed do eiusmod tempor incididunt ut labore et dolore magna "
    "aliqua. Ut enim ad minim veniam, quis nostrud exercitation "
    "ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis "
    "aute irure dolor in reprehenderit in voluptate velit esse cillum "
    "dolore eu fugiat nulla pariatur. Excepteur sint occaecat "
    "cupidatat non proident, sunt in culpa qui officia deserunt "
    "mollit anim id est laborum."
)
test_paragraph_markdown_short = (
    "Lorem **ipsum** dolor sit amet, **consectetur** adipiscing elit, "
    "sed do eiusmod tempor incididunt ut labore et dolore magna "
    "aliqua. Ut enim ad minim veniam, __quis__ nostrud exercitation "
    "ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis "
    "aute irure dolor in reprehenderit in voluptate velit esse cillum "
    "dolore eu fugiat nulla pariatur. Excepteur sint occaecat "
    "cupidatat non proident, sunt in culpa qui officia deserunt "
    "mollit anim id est laborum."
)
test_paragraph_markdown_long = (
    "Lorem **ipsum dolor sit amet, consectetur adipiscing elit, "
    "sed do eiusmod tempor incididunt ut labore et dolore magna "
    "aliqua. Ut enim ad minim veniam, quis nostrud exercitation "
    "ullamco laboris nisi ut aliquip ex ea commodo consequat**. Duis "
    "aute irure dolor in reprehenderit in voluptate velit esse cillum "
    "dolore eu fugiat nulla pariatur. __Excepteur sint occaecat "
    "cupidatat non proident, sunt in culpa qui officia deserunt__ "
    "mollit anim id est laborum."
)


pdf = FPDF()
font_size = 12
pdf.add_page()

for font in ["Helvetica", "Courier"]:
    for text, desc in [
        (test_paragraph_no_markdown, "No Markdown"),
        (test_paragraph_markdown_short, "Short Markdown Section"),
        (test_paragraph_markdown_long, "Long Markdown Section"),
    ]:
        for align in ["L", "J", "C", "R"]:
            # Heading
            pdf.set_font(family=font, style="B", size=font_size)
            pdf.multi_cell(
                190,
                txt="{}: Font = {} {}pt, Alignment = {}".format(
                    desc, font, font_size, align
                ),
            )
            # Test paragraph
            pdf.set_font(family=font, style="", size=font_size)
            pdf.set_y(pdf.y + 3)
            pdf.multi_cell(190, txt=text, align=align, markdown=True)
            pdf.set_x(10)
            pdf.set_y(pdf.y + 5)

pdf.output("markdown_test.pdf")
```

## Environment
* OS: macOS 11.6.2 Big Sur
* Python 3.9.9
* FPDF2: top of master (https://github.com/PyFPDF/fpdf2/commit/9dbffd1285d6d596e1262072f5a70d03b9d69a14)

**Comment by pwt** [comment]
Note also that when I run the same test program with my locally available Montserrat font family, there are also issues with centred and right-aligned text. Please see [markdown_test.pdf](https://github.com/PyFPDF/fpdf2/files/7918496/markdown_test.pdf).

Let me know if you want further details on this.

**Comment by Lucas-C** [comment]
Thank you for the very detailed bug report & excellent minimal reproducing code!

@all-contributors please add @pwt for bug.

**Comment by Lucas-C** [comment]
I made a rapid analysis of this bug:

* when `align == "J"`, the spacing between characters is set here: https://github.com/PyFPDF/fpdf2/blob/2.5.0/fpdf/fpdf.py#L2483

* to improve code readability, `ns` should be renamed `whitespace_count` and `ls` into `chars_total_width`

* when the bug reveals itself, `chars_total_width` is incorrect as it includes markdown characters in its total (`*` / `_` / `-`), because this variable is the total of [get_string_width() calls](https://github.com/PyFPDF/fpdf2/blob/2.5.0/fpdf/fpdf.py#L2450) performed on characters in the `s` variable.

* this is totally related to @gmischler work in https://github.com/PyFPDF/fpdf2/pull/308#issuecomment-1004696020
And should be solved by his PR

**Comment by pwt** [comment]
Thanks for the very quick response to this, and for adding me to contributors :-).

**Comment by gmischler** [comment]
>     * this is totally related to @gmischler work in [feat :: add soft-hyphen for multi-cell #308 (comment)](https://github.com/PyFPDF/fpdf2/pull/308#issuecomment-1004696020)
>       and I believe it should be solved by his PR

While it implements my feature request #291, the PR #308 is actually created and worked on by @oleksii-shyman.
He is indeed trying to address this issue as well, if I understand [#308#issuecomment-1003657924](https://github.com/PyFPDF/fpdf2/pull/308#issuecomment-1003657924) correctly.

**Comment by Lucas-C** [comment]
Oh yes, sorry for the confusion @gmischler 😊

**Comment by oleksii-shyman** [comment]
yes, I am working on this issue and have some results (didn't push updated branch, because there are still things to be cleared)

This is what my code does ->
![image](https://user-images.githubusercontent.com/8827452/150666415-ea518330-f998-43c8-b1e0-6f0ba0418209.png)

Same screenshot on master branch code output ->
![image](https://user-images.githubusercontent.com/8827452/150666449-d5556009-8623-4694-b175-1570b52c9122.png)

I plan to update my PR in the next couple of days
