### ISSUE TITLE
Add a `get_string_height()` method

### ISSUE THREAD

**Issue by larsga** [PyFPDF/fpdf2#336]
The `get_string_width()` method is super useful for calculating the correct positioning of text, but for some uses it's necessary to also know the height of text.

The method signature could be exactly like `get_string_width()`, but return the height of the highest character in the string. No need to handle line breaking or anything like that.

My use case is I'm rendering [phylogenetic trees](https://en.wikipedia.org/wiki/Phylogenetic_tree#/media/File:Tree_of_life_SVG.svg), and a natural scale for the display is to base it on the height of the labels, because that then tells me the minimum viable radius of the circle, and I can scale everything else based on that. Rendering legends and so on also depends on accurately knowing the text height.

**Comment by Lucas-C** [comment]
Interesting use case! In case of a PDF, does your approach with scaling things based on labels height mean you will set the PDF page dimensions based on them too?

For `fpdf2`, I'm not sure that a `get_string_height()` method would make much sense, as text height is currently only based on 2 things:
* the current `FPDF` instance `.font_size` / `.font_size_pt`
* the `h` parameter passed to the `write()` / `cell()` / `multi_cell()` methods

Could you maybe base your layout on those?

Also, will your code be open sourced? If so, when you finish building your phylogenetic tree, could you ping us so that we reference your code? It would make a very pretty showcase for `fpdf2` 😊

**Comment by larsga** [comment]
Page dimensions: yes. I compute the size of the image I'm producing and then I will set the page size to make that fit. Maybe eventually there will be an option to set page size and compute everything from that. In that case, font size will have to be scaled to fit the circle, which still requires accurate estimates of string height.

I totally understand what you mean about the methods that take `h` as a parameter, but I'm not using them, I'm using the `text()` method, because I'm writing exactly placed text with rotation and no line-breaking.

Is `text()` deprecated and I should be using `write()`? If not, then perhaps this method does make sense for `text()`?

The code is open source already [here](https://github.com/larsga/sprake), but it's still a prototype and not suitable for publication-quality output yet. Right now I'm mainly using it as a tool to visualize temporary trees produced as part of research, and slowly iterating it towards something finally usable. I'll be happy to ping you once it's at a usable level.

**Comment by Lucas-C** [comment]
`text()` is not deprecated, it's simply the only method that **only** display a string, and does not have any notion of "surrounding cell dimension". The height of the text it prints only depends on the `.font_size`.

Can you maybe base your layout on the `.font_size`?

**Comment by larsga** [comment]
Yeah, I can probably base it on `font_size`. I'll try that, and come back here if it turns out there are problems with it.

**Comment by Lucas-C** [comment]
Hi @larsga!

Have you been able to test this? 😊

Should we close this issue?

**Comment by larsga** [comment]
Sorry! I do have a workaround, so if you don't want to add this method please feel free to close.
