### ISSUE TITLE
multi_cell table is broken

### ISSUE THREAD

**Issue by mcerveny** [PyFPDF/fpdf2#349]
New features breaks table rendering with multi_cell().
multi_cell() is not rendered if txt="". It breaks table design (cell() is ok).

[test.pdf](https://github.com/PyFPDF/fpdf2/files/8197304/test.pdf)

```python
import fpdf

pdf = fpdf.FPDF(orientation='portrait', unit='mm', format='A4')
pdf.add_page()
pdf.set_font('helvetica',size=10)
for i in range(1,5):
  pdf.multi_cell(20, ln=3, txt=str(i))
pdf.ln(10)
for i in range(1,5):
  pdf.multi_cell(20, ln=3, txt=str(i) if i>2 else "")
pdf.ln(10)
for i in range(1,5):
  pdf.cell(20, txt=str(i))
pdf.ln(10)
for i in range(1,5):
  pdf.cell(20, txt=str(i) if i>2 else "")
pdf.output('test.pdf')
```

**Comment by Lucas-C** [comment]
Hi @mcerveny 

Thanks for reporting this.
The behaviour of `multi_cell()` with empty text input was never tested before.

Here is a unit test we should add, based on your code @mcerveny:
```python
def test_multi_cell_with_empty_contents(tmp_path):  # issue 349
    pdf = fpdf.FPDF()
    pdf.add_page()
    pdf.set_font('helvetica', size=10)
    for i in range(1,5):
        pdf.multi_cell(20, ln=3, txt=str(i))
    pdf.ln(10)
    for i in range(1,5):
        pdf.multi_cell(20, ln=3, txt=str(i) if i>2 else "")
    assert_pdf_equal(pdf, HERE / "multi_cell_with_empty_contents.pdf", tmp_path)
```

Ping @gmischler: what do you think would be the best approach here, to keep the same behaviour as before?
In the new code, `_render_styled_cell_text()` is responsible for incrementing `FPDF.x` but is never called by `multi_cell()` in that case, because `text_lines` is empty.

**Comment by Lucas-C** [comment]
Fixed!
