### ISSUE TITLE
Hindi text is rendered incorrectly

### ISSUE THREAD

**Issue by namastevis** [PyFPDF/fpdf2#365]
While trying to generate a pdf using FPDF2, the Hindi text is not generated correctly. I have tried using different fonts (Gargi, Mangal, Arjun-Wide, Mukta, Lohit) but all give the wrong result similar to what shown below.
Correct hindi text: इण्टरनेट पर हिन्दी के साधन
What is printed:
<img width="269" alt="Screenshot 2022-03-14 at 10 40 13 PM" src="https://user-images.githubusercontent.com/8547885/158224366-546579df-0ec4-4c87-974c-f0bd7fb4ce55.png">

It seems the issue happens in the following two scenarios:
1. 
<img width="33" alt="Screenshot 2022-03-14 at 10 44 12 PM" src="https://user-images.githubusercontent.com/8547885/158225121-675921c8-9f5c-495a-838c-65b5b637900b.png">
When this appears before a character, while printing it moves to the next character.

2. When two consonants are merged to generate a ligature in Hindi, they get split into two.

**Comment by gmischler** [comment]
Unfortunately, this is not a trivial problem to solve, and fpdf is a deliberately simple PDF generation library.

What you're seeing is a lack of support for automatic ligatures, more specifically [Devaganari conjuncts](https://en.wikipedia.org/wiki/Devanagari_conjuncts). There are hundreds of those, many more than normal characters. A supporting font will include a table of character sequences that are supposed to be substituted for a ligature glyph. The most complex example in your text is this (separated with spaces on the left side, so the browser does not combine them):
न्  ् द  ी  ▶️  न्दी
Yes, that's four (4) individual unicode characters in the text that together should result in a single glyph.

Unfortunately, fpdf currently operates on a character-by-character basis when first determining the width of each character and later printing a suitable glyph from the selected font. Supporting ligatures would require their substitution to happen as the very first step. We would also need a custom datastructure to represent them, because they cannot be represented by a python unicode character.

Technically all of that it is certainly possible, but I wouldn't hold my breath for it right now. Anyone who knows enough about the internal structure of ttf fonts is of course welcome to contribute...

Btw: Ligatures exist in many other writing systems. And another peculiarity that might also be interesting is contextual forms, where a different glyph is used for the same character, depending on whether it appears at the beginning, the middle, or the end of a word, or isolated (common eg. in Arabic, Hebrew, Mongolian, etc.).

**Comment by Lucas-C** [comment]
This issue also affects Tamil text: https://github.com/carlhiggs/global_scorecards/issues/7

**Comment by MayankFawkes** [comment]
unfortunately still the same problem, [Pillow ](https://github.com/python-pillow/Pillow) had the same problem rendering fonts then they added [font layout engine](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.truetype) and [ImageFont.Layout.RAQM](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.PIL.ImageFont.Layout.RAQM) which solves the problem i am not really good but ig [libraqm](https://github.com/HOST-Oman/libraqm) can help if someone can add it in fpdf2

**Comment by Lucas-C** [comment]
This is an interesting lead, thank you @MayankFawkes.
One limitation is that [libraqm](https://github.com/HOST-Oman/libraqm) is a C library that hasn't been packaged as a Python package, AFAIK.
Hence it won't be straightforward for `fpdf2` to have a dependency on it.

**Comment by MayankFawkes** [comment]
@Lucas-C there are some ways we can use it like, The build binary of libraqm is available, We can just use the binary of [libraqm](https://github.com/HOST-Oman/libraqm) for Linux is it really simple `apt-get install libraqm0 libraqm-dev` and for windows there are third party builds available, We can release an optional update which support of libraqm engine so the problem of rendering hindi and other Unicode fonts will get solved.

First, there is the [ctypes](http://docs.python.org/library/ctypes.html) module in the standard library. It allows you to load a dynamic-link library (DLL on Windows, shared libraries .so on Linux) and call functions from these libraries, directly from Python. Such libraries are usually written in C. -- [source ](https://stackoverflow.com/questions/10202306/python-bindings-how-does-it-work/10202569#10202569)

dependency problem: Pillow uses libraqm and doesn't care about installing it with pillow because it is optional if we want pillow to decode fonts properly then we have to manually install it, we can do the same and if we want to provide it as a dependency the best way to make our build for different architecture and put it in the pip wheel file.

to add libraqm as dependency: there is a lib written in c/c++ for decoding qr and barcodes called [zbar](https://github.com/mchehab/zbar) and they also have binary files so someone made a warper for that called [pyzbar](https://github.com/NaturalHistoryMuseum/pyzbar) and this is how he building wheel file to add support of zbar binary [link](https://github.com/NaturalHistoryMuseum/pyzbar/blob/master/build.sh) just adding binaries to wheel 

I am dropping some more links to add `c` support in python with `ctypes`
[digitalocean](https://www.digitalocean.com/community/tutorials/calling-c-functions-from-python)
[betterprogramming](https://betterprogramming.pub/how-to-create-a-python-wrapper-for-c-c-shared-libraries-35ffefcfc10b)

**Comment by gmischler** [comment]
If fpdf2 were linux-only, using stuff like ctypes would be no problem.
But for Windows, MacOS, and potentially other systems, only dependencies that can be installed via pip are practially realistic.

This specific issue here is "only" about ligatures, which is primarily necessary for indic scripts.
For scripts derived from aramaic (arabic, hebrew, mongolian, etc.), a more complete solution would indeed also handle [bidi](https://www.unicode.org/reports/tr9/) text and positional context, so having a feature complete "layout engine" would be nice.

A python implementation of the bidi algorithm is available in [python-bidi](/MeirKriheli/python-bidi), though it doesn't look particularly complicated, so we could easily roll our own.
There's also [python-arabic-reshaper](https://github.com/mpcabd/python-arabic-reshaper). It reverses the direction and does the necessary contextual and ligature substitutions. Unfortunately, all the substitutions are hardcoded, so it is suitable for arabic and kurdish text *only*. But it can still serve as an example on a possible way to proceed and what issues to look out for.

A general solution to ligatures requires a lookup of the substitutions in the font data. This seems straightforward, but we'll have to see what pitfalls we run into with it.
Note that we have some requirements that I haven't yet seen satisfied with any of the existing modules. Among other things, for any ligature glyph sequence, we need to preserve information about the original unicode code points. Those will be added as supplementary info to the PDF text, so that when you copy from a PDF viewer, you get the original unsubstituted text back.

So I suspect we can't just slap on a few more dependencies and let those do the work for us.
I'd suggest a step-by-step approach, that we have essentially have already begun with:

1. switch to fonttools (currently being worked on: #477)
1. support ligature substitutions
1. support contextual substitutions
1. support bidi text
1. support vertical text

Obviously all of this won't happen within a few weeks. Care should also be taken at any step not to take the possible requirements of the following steps into account, at least as far as can be predicted at the given time.

**Comment by Lucas-C** [comment]
@andersonhc PR https://github.com/PyFPDF/fpdf2/pull/820 has been merged today.

Could you test if that solved your issue @namastevis?

You can install `fpdf2` directly from the `master` branch of this repo with this command:

    pip install git+https://github.com/PyFPDF/fpdf2.git@master

The documentation is there: https://pyfpdf.github.io/fpdf2/TextShaping.html

**Comment by mohindra9211** [comment]
I continue to encounter the same problem, and unfortunately, it remains unresolved. I have experimented with various Hindi Devanagari fonts, but the text still does not render correctly.
-----------------------------------------------------------------
Original Text = परी कथाएँ काल्पनिक होते हुए भी मन को उड़ान देने वाली और शिक्षाप्रद होती हैं।
-----------------------------------------------------------------
FPDF2 output
![Screenshot 2023-09-30 193610](https://github.com/py-pdf/fpdf2/assets/26268283/ef7fc4c7-bb7e-46c6-abeb-d5d992f35f3d)
-----------------------------------------------------------------
It seems the issue happens in the following two scenarios:
1.
<img width="33" alt="158225121-675921c8-9f5c-495a-838c-65b5b637900b" src="https://github.com/py-pdf/fpdf2/assets/26268283/5c6edb0f-4a9b-425c-8dd9-0f718552954d">
2. When this appears before a character, while printing it moves to the next character.

When two consonants are merged to generate a ligature in Hindi, they get split into two.

I humbly seek your support. In my role as a data scientist, I have explored different libraries for PDF generation and have observed that FPDF consistently delivers better outcomes in comparison to ReportLab, which encounters the same issue.

**Comment by andersonhc** [comment]
@mohindra9211 did you try "set_text_shaping()"?

here is the small test I did:
```python
from fpdf import FPDF

text= "परी कथाएँ काल्पनिक होते हुए भी मन को उड़ान देने वाली और शिक्षाप्रद होती हैं।"

pdf = FPDF()
pdf.add_page()
pdf.add_font(family="Mangal", fname="C:\\Apps\\fpdf2\\test\\text_shaping\\Mangal 400.ttf")
pdf.set_font("Mangal", size=40)
pdf.set_text_shaping(False)
pdf.multi_cell(w=pdf.epw, txt=text, new_x="LEFT", new_y="NEXT")
pdf.ln()
pdf.set_text_shaping(True)
pdf.multi_cell(w=pdf.epw, txt=text, new_x="LEFT", new_y="NEXT")
pdf.output("hindi.pdf")
```

And the results with text shaping enabled looks correct.

**Comment by mohindra9211** [comment]
> andersonhc

Dear AndersonHC,

I want to express my sincere gratitude for your assistance. You've helped me resolve a significant issue. However, I've noticed a minor problem in the output, and I suspect it might be related to the font. I'll try using different fonts to see if that resolves the issue.

Thank you once again for your valuable help.

![123](https://github.com/py-pdf/fpdf2/assets/26268283/bcb02b32-5492-4d6b-8cd5-5c41638f2829)

**Comment by andersonhc** [comment]
Can you tell me what font and text you used?
I'd love to have all those glitches corrected.

**Comment by mohindra9211** [comment]
> Can you tell me what font and text you used? I'd love to have all those glitches corrected.

This problem is solved
The "Karma" font (in the file "Karma-Regular.ttf") is the most suitable choice for displaying Hindi text. I have included a sample for your reference.

Thank you once again for your valuable help.

![2](https://github.com/py-pdf/fpdf2/assets/26268283/832cb79e-4171-46dc-b464-42f32d9c989c)

**Comment by mohindra9211** [comment]
Tomorrow, I'll provide a list of fonts that correctly support Hindi text. Please incorporate this information into your document. It will be particularly beneficial for FPDF2 users, especially those in India. I appreciate your support and prompt response. Thank you.

**Comment by mohindra9211** [comment]
> Can you tell me what font and text you used? I'd love to have all those glitches corrected.

Tomorrow, I'll provide a list of fonts that correctly support Hindi text. Please incorporate this information into your document. It will be particularly beneficial for FPDF2 users, especially those in India. I appreciate your support and prompt response. Thank you.

**Comment by gmischler** [comment]
Those fonts that don't work with fpdf2, do they produce correct results with other software?
If so, then maybe you can provide a list of that category as well.
If we can't make them work on our own, then it may actually be that harfbuzz (the library that does the actual text shaping) is unable to handle them. In that case, the developers there might be interested to learn about it.

**Comment by sanjaykare** [comment]
> @mohindra9211 did you try "set_text_shaping()"?
> 
> here is the small test I did:
> 
> ```python
> from fpdf import FPDF
> 
> text= "परी कथाएँ काल्पनिक होते हुए भी मन को उड़ान देने वाली और शिक्षाप्रद होती हैं।"
> 
> pdf = FPDF()
> pdf.add_page()
> pdf.add_font(family="Mangal", fname="C:\\Apps\\fpdf2\\test\\text_shaping\\Mangal 400.ttf")
> pdf.set_font("Mangal", size=40)
> pdf.set_text_shaping(False)
> pdf.multi_cell(w=pdf.epw, txt=text, new_x="LEFT", new_y="NEXT")
> pdf.ln()
> pdf.set_text_shaping(True)
> pdf.multi_cell(w=pdf.epw, txt=text, new_x="LEFT", new_y="NEXT")
> pdf.output("hindi.pdf")
> ```
> 
> And the results with text shaping enabled looks correct.

I tried with the given code but it's not working & tried to Mangal_Regular font. May font problem. please correct it.
![image](https://github.com/py-pdf/fpdf2/assets/107122417/76c48d6f-a016-4d9b-a9e6-1edb044bf234)

**Comment by mohindra9211** [comment]
> > @mohindra9211 did you try "set_text_shaping()"?
> > here is the small test I did:
> > ```python
> > from fpdf import FPDF
> > 
> > text= "परी कथाएँ काल्पनिक होते हुए भी मन को उड़ान देने वाली और शिक्षाप्रद होती हैं।"
> > 
> > pdf = FPDF()
> > pdf.add_page()
> > pdf.add_font(family="Mangal", fname="C:\\Apps\\fpdf2\\test\\text_shaping\\Mangal 400.ttf")
> > pdf.set_font("Mangal", size=40)
> > pdf.set_text_shaping(False)
> > pdf.multi_cell(w=pdf.epw, txt=text, new_x="LEFT", new_y="NEXT")
> > pdf.ln()
> > pdf.set_text_shaping(True)
> > pdf.multi_cell(w=pdf.epw, txt=text, new_x="LEFT", new_y="NEXT")
> > pdf.output("hindi.pdf")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And the results with text shaping enabled looks correct.
> 
> I tried with the given code but it's not working & tried to Mangal_Regular font. May font problem. please correct it. ![image](https://user-images.githubusercontent.com/107122417/277960606-76c48d6f-a016-4d9b-a9e6-1edb044bf234.png)

Read "AttributeError" carefully and write the correct path

**Comment by sanjaykare** [comment]
> > > @mohindra9211 did you try "set_text_shaping()"?
> > > here is the small test I did:
> > > ```python
> > > from fpdf import FPDF
> > > 
> > > text= "परी कथाएँ काल्पनिक होते हुए भी मन को उड़ान देने वाली और शिक्षाप्रद होती हैं।"
> > > 
> > > pdf = FPDF()
> > > pdf.add_page()
> > > pdf.add_font(family="Mangal", fname="C:\\Apps\\fpdf2\\test\\text_shaping\\Mangal 400.ttf")
> > > pdf.set_font("Mangal", size=40)
> > > pdf.set_text_shaping(False)
> > > pdf.multi_cell(w=pdf.epw, txt=text, new_x="LEFT", new_y="NEXT")
> > > pdf.ln()
> > > pdf.set_text_shaping(True)
> > > pdf.multi_cell(w=pdf.epw, txt=text, new_x="LEFT", new_y="NEXT")
> > > pdf.output("hindi.pdf")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And the results with text shaping enabled looks correct.
> > 
> > 
> > I tried with the given code but it's not working & tried to Mangal_Regular font. May font problem. please correct it. ![image](https://user-images.githubusercontent.com/107122417/277960606-76c48d6f-a016-4d9b-a9e6-1edb044bf234.png)
> 
> Read "AttributeError" carefully and write the correct path

fixed, the file path was not correct. Thank you! 
one more question can we use Hindi text with HTML tag?

**Comment by mohindra9211** [comment]
To gain a better understanding of fpdf2, it is advisable to peruse the fpdf2 documentation along with its tutorials. It's worth noting that you can incorporate both Hindi and English text into your documents, depending on your coding proficiency.
