### ISSUE TITLE
Getting "ImportError: DLL load failed while importing _imaging: Access is denied." error while importing FPDF2

### ISSUE THREAD

**Issue by kargan49** [PyFPDF/fpdf2#449]
```
Traceback (most recent call last):
  File "e:\master_entry_app_files\app.py", line 31, in <module>
    import gl_data_entry as gldeCls
  File "e:\master_entry_app_files\gl_data_entry.py", line 8, in <module>
    from pdf_generation_from_list import text_to_pdf
  File "e:\master_entry_app_files\pdf_generation_from_list.py", line 5, in <module>
    from fpdf import FPDF
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\fpdf\__init__.py", line 4, in <module>
    from .fpdf import (
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\fpdf\fpdf.py", line 37, in <module>
    from PIL import Image
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 89, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: Access is denied.
```

Because of the above error, could not import the FPDF2 module. Kindly advise for rectifying the issue.

**Comment by RedShy** [comment]
Hi! Seems more related to `Pillow` than `fpdf2` to me, have you tried to upgrade `Pillow?`

**Comment by kargan49** [comment]
> Hi! Seems more related to `Pillow` than `fpdf2` to me, have you tried to upgrade `Pillow?`

Yes, upgraded Pillow to latest version didn't resolve the issue.

**Comment by kargan49** [comment]
Sometimes, the issue gets resolved when I restart the pc, but the issue still persists.

**Comment by RedShy** [comment]
Seems a problem with permissions in reading the `.pyd` files in `Python39\lib\site-packages\PIL\`

**Comment by Lucas-C** [comment]
Could you try the following commands and copy their output here please?
```
pip --version
pip freeze
dir C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL
pip uninstall Pillow
pip install --upgrade Pillow
```

**Comment by gmischler** [comment]
> File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 89, in <module>
>     from . import _imaging as core

Looks like you have Python (or at least Pillow) installed in user space.
Is this the only installation on that system?
Does the error possibly happen when you try to run the code as another user?

**Comment by kargan49** [comment]
> > File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 89, in <module>
> >     from . import _imaging as core
> 
> Looks like you have Python (or at least Pillow) installed in user space.
> Is this the only installation on that system?
> Does the error possibly happen when you try to run the code as another user?

This error occurs in my office pc, also the user does not have admin rights.

**Comment by gmischler** [comment]
> I'm not aware of what user space is.

On Windows, "user space" is anything below this:
>> File "C:\Users\

where the files are typically owned by the respective user.
If you try to access such a file from a different login, you may be denied access. But since you seem to be using the default Windows user account (unusual for an office machine), that is unlikely to be the case here though.

> This error occurs in my office pc, and the user does not have admin rights, and there are other installations also.

Generally speaking: "Access is denied" means that the system is preventing you from reading that file, which is outside the control of fpdf2 or even Python. Since on Windows the default file opening mode is exclusive access, any other process accessing the same file at the same time may cause this. The possibilities may range from looking at the code in an editor to a virus scanner checking it out. Depending on the system version, even just Windows Explorer showing the metadata of the file in the preview or details pane may cause trouble.

**Comment by kargan49** [comment]
> > I'm not aware of what user space is.
> 
> On Windows, "user space" is anything below this:
> >> File "C:\Users\
> 
> where the files are typically owned by the respective user.
> If you try to access such a file from a different login, you may be denied access. But since you seem to be using the default Windows user account (unusual for an office machine), that is unlikely to be the case here though.
> 
You are right, I'm not using the default windows user account.  It's "C:\Users\my-employee-number"

**Comment by kargan49** [comment]
> Could you try the following commands and copy their output here please?
> ```
> pip --version
> pip freeze
> dir C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL
> pip uninstall Pillow
> pip install --upgrade Pillow
> ```

I'm getting message as "Access is denied" for the above commands

**Comment by Lucas-C** [comment]
Thanks for trying.

You probably should get in touch with your collegues in charge of managing employees computers,
as the underlying issue seems to be your access rights.
Your company policy probably limits you in the commands you can run on your computer,
but this has nothing to do with `fpdf2`.

Where you able to install other Pypi packages and use them in a script?
Are your collegues able to install & use `fpdf2` or other Python libraries?

**Comment by kargan49** [comment]
> Thanks for trying.
> 
> You probably should get in touch with your collegues in charge of managing employees computers,
> as the underlying issue seems to be your access rights.
> Your company policy probably limits you in the commands you can run on your computer,
> but this has nothing to do with `fpdf2`.
> 
> Where you able to install other Pypi packages and use them in a script?
> Are your collegues able to install & use `fpdf2` or other Python libraries?

Yes, I could install Pypi packages only by using the command "python -m pip install package_name -f ./ --no-index--no-deps"
I download the package from pypi.org and use the above command to install any package.

**Comment by Lucas-C** [comment]
OK. Then the difference between the packages you successfully installed and `fpdf2` could be that `fpdf2` depends on Pillow which is packaged as binary because it includes compiled C code.

Its likely that so far you did not use any Python package including C compiled code, and thus did not have any issue until now.

I don't have any proper solution to offer you, that's just a potenial explanation.
Again, you will probably find more help with your enterprise colleagues, especially the Windows system administrators.

Also, in the next release, `fpdf2` will be able to run without Pillow: https://github.com/PyFPDF/fpdf2/blob/master/fpdf/fpdf.py#L37
But without that dependency you won't be able to embed any image.

**Comment by Lucas-C** [comment]
Hi @kargan49!

Do you still need assistance with this?
Else could we close this issue?

**Comment by kargan49** [comment]
> Hi @kargan49!
> 
> Do you still need assistance with this?
> Else could we close this issue?

Yes, this thread can be closed.
