### ISSUE TITLE
Is there a way to set row height according to the highest column height in the row without calculating the highest column height?

### ISSUE THREAD

**Issue by AggarwR7** [PyFPDF/fpdf2#494]

**Comment by AggarwR7** [comment]
Hi Team,

I am using "multi_cell" to add data in the table. But if the column data is bigger, I want the whole row to take the height of the highest column height in the row while printing. I went through the listed issues, everyone seems to be calculating the max height of the whole row first, and then printing it according to the max height. My use case involves printing thousands of rows of data, and going by this approach would increase the time complexity and rendering time of the PDF drastically, as it's double iterations.

Is there any way that we can achieve this functionality without the prior calculation of the max cell height?

Attaching the PDF snippet for your reference.

<img width="168" alt="image" src="https://user-images.githubusercontent.com/90680193/185152981-21138e5b-f3e1-4a39-a34c-9b3e41778bbc.png">

**Comment by Lucas-C** [comment]
Hi @AggarwR7
This has been discussed in past issues.
Could this code snippet be useful to you?
https://github.com/PyFPDF/fpdf2/issues/91#issuecomment-813033012

**Comment by Lucas-C** [comment]
> Hi @Lucas-C , I went through this code snippet earlier also, before posting this question, and what I could see is that here also they're calculating the "height of highest cell" prior to printing the row, running two "for" loops.

Indeed they do.

> Is there any way that we can achieve this functionality without the prior calculation of the max cell height?

No, sorry, to be clear: currently `fpdf2` offers no other way to do so.

**Comment by gmischler** [comment]
@AggarwR7 , you should be able to create a table in a single loop, as long as you can live with certain limitations.
* for each row
  * remember the fpdf current y position as row top
  * remember the row bottom (initialize with row top)
  * for each column
    * render cell contents with new_y="NEXT"
    * if the new fpdf current y is lower than the current bottom, update the bottom
    * reset fpdf current y to row top
  * draw cell outlines for the whole row as needed
  * set the fpdf current y to the current bottom

There are several things that are impossible to do within a single loop, because you can only know the actual height of each row after its contents are already rendered:
* let `multi_cell()` draw the cell outlines. 
* use background colors for cells.
* align cell content vertically.

**Comment by Lucas-C** [comment]
@AggarwR7: does that answer your question?
Do you any other interrogation or can this issue be closed?

**Comment by Lucas-C** [comment]
In absence of any respone, closing this for now.
Please add a comment or reopen another issue if you still have a problem regarding this
