### ISSUE TITLE
Why am I getting warning FFTM NOT subset; don't know how to subset; dropped?

### ISSUE THREAD

**Issue by astrike30** [PyFPDF/fpdf2#600]
Hi, I am trying to add the font `DejaVuSans.tff` from the free font pack. When I run the following code:

```
pdf = FPDF()
pdf.add_font("DejaVuSans", fname="DejaVuSans.ttf")
pdf.set_font("DejaVuSans", size=10)
pdf.add_page()
pdf.cell(30, 10, "Test cell")
pdf.output("statement2.pdf", "F")
```

I get the warning `FFTM NOT subset; don't know how to subset; dropped`. The pdf seems to generate fine, am I doing something wrong? Otherwise is there a way to fix this or at least suppress the warning?

Thanks :)

**Comment by Lucas-C** [comment]
I tested your code with [this DejaVuSans.ttf font file](https://github.com/PyFPDF/fpdf2/blob/master/test/fonts/DejaVuSans.ttf) and it works fine.
* where does your `DejaVuSans.ttf` file comes from?
* what version of `fpdf2` are you using?

**Comment by gmischler** [comment]
This is a message from the [fonttools library](https://github.com/fonttools/fonttools/blob/25bcde5f318415be7d4d37728090dc54758d0704/Lib/fontTools/subset/__init__.py#L3001). It tells you that it doesn't know how to add the elements of the `FFTM` table found in the font file to the glyphs included in the PDF file. The `FFTM` table appears to be a "FontForge Time Stamp Table", which looks like proprietary data that gets added to a font file when editing it with the FontForge editor.

Since such data has no meaning in a PDF file, you can safely ignore that message.

From our side, we could consider adding this table type to the [list of excluded tables](https://github.com/PyFPDF/fpdf2/blob/11181be58b05c53616c9b91e8c7a90bd8fe2d958/fpdf/output.py#L529) when subsetting. On one hand, there might be an arbitrary number of proprietary data someone adds to font files, which we can't all cover there preemptively just to avoid a warning message. On the other hand, FontForge appears to be quite a popular font editor, so in this case it might be worth it.

**Comment by Lucas-C** [comment]
@astrike30: without any answer from you, I'm planning to close this _issue_.

> From our side, we could consider adding this table type to the [list of excluded tables](https://github.com/PyFPDF/fpdf2/blob/11181be58b05c53616c9b91e8c7a90bd8fe2d958/fpdf/output.py#L529) when subsetting. On one hand, there might be an arbitrary number of proprietary data someone adds to font files, which we can't all cover there preemptively just to avoid a warning message. On the other hand, FontForge appears to be quite a popular font editor, so in this case it might be worth it.

Agreed, I'm going to add this to the list of excluded tables, with a comment explaining why
