### ISSUE TITLE
What is the propper way to go back to page 2 and write index

### ISSUE THREAD

**Issue by miguelmpn** [PyFPDF/fpdf2#611]
Hello, 
I'm generating one PDF document, at the end I'll have a Dict with titles and pages and I need to go back to page 2 and write the index.
The index needs to be generated at the end of the document generation because only then I will know the page numbers.

What is the proper way of doing this?

At the moment I count the titles and generate enough blank pages to withstand the index, then, in the end, I use self.page = 2 to write the index on the previously added blank pages.
But somehow there is something missing because it looks well on the PDF, but when I use [this ](https://stackoverflow.com/questions/49965818/convert-pdf-to-docx-with-python#answer-63255120)PDF to Docx, the index page goes to page 1, while all others perform well.

**Comment by Lucas-C** [comment]
In order to support this feature, we provide a [insert_toc_placeholder](https://pyfpdf.github.io/fpdf2/fpdf/fpdf.html#fpdf.fpdf.FPDF.insert_toc_placeholder) method:
https://pyfpdf.github.io/fpdf2/DocumentOutlineAndTableOfContents.html

It's a bit surprising that you first build a PDF and then convert it to a Word `.docx` file.
Usually it's a lot simpler to go the other way round, generating a document with Word or LibreOffice, and then export it as PDF

**Comment by miguelmpn** [comment]
No problem thank you, I'll update this thread if I find a solution. (I'll think of it a bit more)

**Comment by Lucas-C** [comment]
I hope my answers helped you in some way 😊

I'm closing this for now, but feel free to reopen this issue if need be.
And I'd be curious to know how you solved this, so an update is always welcome 👍

**Comment by Lucas-C** [comment]
Also, the approach you described:

> At the moment I count the titles and generate enough blank pages to withstand the index, then, in the end, I use self.page = 2 to write the index on the previously added blank pages.

...is exactly what we do in `_insert_table_of_contents()`: https://github.com/PyFPDF/fpdf2/blob/2.6.0/fpdf/fpdf.py#L3890
