### ISSUE TITLE
set_encryption breaks URL links

### ISSUE THREAD

**Issue by Lucas-C** [PyFPDF/fpdf2#672]
Unit test demonstrating the bug:
```python
def test_encryption_with_hyperlink(tmp_path):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("helvetica")
    pdf.cell(txt="hyperlink", link="https://github.com/PyFPDF/fpdf2")
    pdf.set_encryption(owner_password="fpdf2")
    assert_pdf_equal(pdf, HERE / "encryption_with_hyperlink.pdf", tmp_path, generate=True)
```

Bug reported by @SfinxV in #194

**Comment by andersonhc** [comment]
endobj
3 0 obj
<<
/Annots [<</A <</S /URI /URI (https://github.com/PyFPDF/fpdf2)>>
/Border [0 0 0]
/F 4
/Rect [31.18 813.54 79.19 801.54]
/Subtype /Link
/Type /Annot>>]
/Contents 4 0 R
/Group <</Type /Group /S /Transparency /CS /DeviceRGB>>
/Parent 1 0 R
/Resources 6 0 R
/Type /Page
>>

The problem here is the annotation string is not being encrypted by fpdf2. The client is decrypting the unencrypted link and getting the bad result.
