### ISSUE TITLE
No module named fpdf.enums 

### ISSUE THREAD

**Issue by francescoavant** [PyFPDF/fpdf2#776]
Hi, from today i encounter this problem when running my application:

`.......[redacted].......line 20, in <module>`\
    `from fpdf.enums import XPos, YPos`\
`ModuleNotFoundError: No module named 'fpdf.enums'`

These are my imports in the code:
`from fpdf import FPDF` \
`from fpdf.enums import XPos, YPos`

Has anyone the same problem?

**Comment by Lucas-C** [comment]
Hi @francescoavant and welcome 😊

When opening this bug report, you should have seen this template:
https://raw.githubusercontent.com/PyFPDF/fpdf2/master/.github/ISSUE_TEMPLATE/bug_report.md

Could you please provide the information requested in this template?

Without them, we won't be able to help you much.
It is especially important to know what version of `fpdf2` you are using.

Does the error happens if you put this single line in a `bug_repro.py` script and execute it with Python?
```
from fpdf.enums import XPos, YPos
```

**Comment by francescoavant** [comment]
Hi @Lucas-C, sorry for the missing information.

I resolved the problem that occurs for my venv misconfiguration.

Thank you

**Comment by Lucas-C** [comment]
Glad that you found the solution to your problem!
