### ISSUE TITLE
`test_share_images_cache` test randomly fails

### ISSUE THREAD

**Issue by qarmin** [PyFPDF/fpdf2#833]
**Error details**
This test depends on performance of computer which is bad.

Once it failed because duration time was 0.295s and was smaller than 0.3s

https://github.com/PyFPDF/fpdf2/blob/56517bb0c4e593acce2f32783f9bc3597d127cdb/test/image/test_load_image.py#L47-L70

**Environment**
* **Operating System**: Ubuntu 22.04
* **Python version**: 3.7.17
* **`fpdf2` version used**: master

**Comment by Lucas-C** [comment]
Hi @qarmin

As a maintainer, I really value having tests ensuring performance of `fpdf2` stays good and does not degrade due to the introduction of cpu-intensive code in PRs.

I agree that those tests can be sometimes flaky, and depend on the user hardware performances, which is annoying.

Apart from reporting the problem you had (which is OK),
do you have any constructive suggestion in order to improve this?

in other performance-related tests we use timing averages in order to be more resilient:
https://github.com/PyFPDF/fpdf2/blob/master/test/conftest.py#L252
We could adopt a similar strategy in `test_share_images_cache()`

**Comment by Lucas-C** [comment]
Hi @qarmin

Unless you have something more to add on the subject, I'm going to close this issue soon
