### ISSUE TITLE
Error in html table rendering when html tags are used inside a cell

### ISSUE THREAD

**Issue by stenci** [PyFPDF/fpdf2#845]
The following code should create a table with 3 rows and 3 columns, instead the 2nd row contains 5 columns.

The two `font` tags are correctly interpreted and they have the expected effect on the font, but they also seem to be interpreted as `td`.

**Example code**
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.write_html("""
<table border=1>
  <thead>
    <tr>
      <th>Column 1</th>
      <th>Column 2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td align="center">Cell 1</td>
      <td align="center">Cell 2</td>
    </tr>
    <tr>
      <td align="center">Cell 1</td>
      <td align="center">Some <font size=7>small</font> and some <font size=20>large</font></td>
    </tr>
    <tr>
      <td align="center">Cell 1</td>
      <td align="center">Cell 2</td>
    </tr>
  </tbody>
</table>
""")
pdf.output("html.pdf")
```
**Example output**
![image](https://github.com/PyFPDF/fpdf2/assets/5955495/00f8339a-4c67-4a54-826b-1ad0e5036fd6)

**Environment**
* **Operating System**: Windows
* **Python version**: 3.7
* **`fpdf2` version used**: 2.7.4

**Comment by Lucas-C** [comment]
Hi @stenci and thank you for the precise bug report 👍

`<font>` tags are currently not supported inside `<td>` elements.

FYI, when using the latest version of `fpdf2` from the `git` `master` branch (_cf._ https://pyfpdf.github.io/fpdf2/#installation ),
you would get the following error from the `fpdf/table.py` module:
```
fpdf.errors.FPDFException: Inconsistent column count detected on row 3: it has 5 columns, whereas the top row has 2.
```

We could improve that error message, or generate a more explicit one in the `html.py` module in that case.

Adding support for `<font>` tags in `<td>` elements would be a lot more difficult,
as it would mean supporting table sub-cells.

For reference, this issue is related to issue #640: both reveal fundamental limitations of `fpdf2` HTML renderer,
that does not support rendering of nested elements, whereas the HTML spec totally allows them.

**Comment by Lucas-C** [comment]
I opened PR #852 in order to improve our documentation and generate a clearer error message

**Comment by stenci** [comment]
> I opened PR #852 in order to improve our documentation and generate a clearer error message
> 
> Would you like to review it @stenci? 😊

I am not familiar with github. I clicked on the PR, I noticed a "review changes" button, clicked on it and approved.
The changes seem to fully address the problem, and some more.
Thank you for addressing this, and doing it so quickly.

**Comment by Lucas-C** [comment]
Thank you for your feedback @stenci 🙂 

I merged the PR
