### ISSUE TITLE
Format imports with isort

### ISSUE THREAD

**Issue by Tolker-KU** [PyFPDF/fpdf2#864]
It seems that the format and order of imports isn't consistent across the project. The tool isort can easily fix this. It has a pre-commit hook, so it is plug-and-play with the existing setup. I've played around with it in this branch: https://github.com/Tolker-KU/fpdf2/tree/isort

**Comment by Lucas-C** [comment]
Hi @Tolker-KU 😊

This is an interesting suggestion.

I know about `isort` and other similar tools.

I'm not really convinced there is much benefit to it.
And I'd prefer not too adopt such tools just "because it's fun / it pleases my OCD" 😅
They always add a slight cost for contributors to setup a development environment (today even the pre-commit hook is optional) and/or add steps to the CI pipeline.

Sometimes the benefits outweigh the costs, but I'm not convinced regarding `isort`.
We already use `black`, and I think that may be enough.

**Comment by Tolker-KU** [comment]
The motivation behind this suggestion is that I incurred some overhead when making the changes in #863 - specifically when adding new imports - as it wasn't clear to me what order/format this project uses when it comes to imports. Having a tool like `isort` makes sure the order and format is automatically consistent and thus taking out some overhead when changing code. 

I know we get some overhead in pipelines, but when `black` is already used this overhead is minimal as I see it, as `isort` can be run in the same environments/steps.

AFAIK `black` doesn't really do anything to imports expect for making sure that line lengths aren't too long

**Comment by gmischler** [comment]
> The motivation behind this suggestion is that I incurred some overhead when making the changes in #863 - specifically when adding new imports - as it wasn't clear to me what order/format this project uses when it comes to imports.

Am I missing something here? All I see you doing in this context is adding `import sys` in several test files, and an additional `import pytest` in one of them. What specific difficulties did you encounter in doing that?

It is pretty much common sense that standard library imports should come first, third-party libraries second, and project internal ones last, since that is how they necessarily depend on each other. But even that is more a matter of style than a technical requirement.

How exactly does any of that justify the introduction of an extra tool into the workflow?
Isn't blacks rigidity annoying enough for you yet? :wink:

**Comment by Tolker-KU** [comment]
> > The motivation behind this suggestion is that I incurred some overhead when making the changes in #863 - specifically when adding new imports - as it wasn't clear to me what order/format this project uses when it comes to imports.
> 
> Am I missing something here? All I see you doing in this context is adding `import sys` in several test files, and an additional `import pytest` in one of them. What specific difficulties did you encounter in doing that?

I agree that the changes were minor - and I wouldn't say that I encountered difficulties in making them. But I did encounter some overhead as I had to think about where to put the imports and how to format that. This overhead can be avoided by using import formatting tools

> 
> It is pretty much common sense that standard library imports should come first, third-party libraries second, and project internal ones last, since that is how they necessarily depend on each other. But even that is more a matter of style than a technical requirement.
> 

I agree! But you have to know this convention and you have to use brain power to adhere to it - even though it might be minimal brain power for experienced developers.

> How exactly does any of that justify the introduction of an extra tool into the workflow? Isn't blacks rigidity annoying enough for you yet? 😉

In my opinion the fact the developer don't have to know and worry about the styling/formatting convention more than out-weights the tiny overhead from pipelines running isort. Also I'm actually not annoyed by black - I see it as a useful tool to keep formatting consistent. Using black I can just type out code without breaking long lines, keeping spacing consistent, etc. and then just run the tool before pushing.

Also for I'm used to using quite a lot of tools, which might be the explantation for our seemingly different opinions. I don't propose that this project should use all of these tools 😊 
* [black](https://black.readthedocs.io/en/stable/)
* [isort](https://pycqa.github.io/isort/)
* [pycln](https://hadialqattan.github.io/pycln/#/)
* [pyupgrade](https://github.com/asottile/pyupgrade)
* [flake8](https://flake8.pycqa.org/en/latest/) (with a lot of plugins)
* [vulture](https://github.com/jendrikseipp/vulture)
* [mypy](https://mypy-lang.org/)
* [setup-cfg-fmt](https://github.com/asottile/setup-cfg-fmt)

**Comment by gmischler** [comment]
> But I did encounter some overhead as I had to think about where to put the imports and how to format that. 

So next time you get confronted with the same question you can just apply what you've learned here, with no mental overhead whatsoever! :wink:

> Also for I'm used to using quite a lot of tools, which might be the explantation for our seemingly different opinions.

In a project with hundreds of developers, thousands of source files, and multi-page import blocks I would probably also consider using such a tool (after questioning the sanity of the fundamental system architecture).

In our case with about two dozen source files, most of which only have a handful of imports, there is really no point.
Just using common sense is perfectly adequate here, and even writing down a formal "imports formatting policy" would already be overkill.

Since we also don't have a pointy haired boss who suddenly demands that everything be sorted alphabetically, problem solved! :wink:

**Comment by Lucas-C** [comment]
> In our case with about two dozen source files, most of which only have a handful of imports, there is really no point.

One could argue that we also have a lot of unit test files where such tool could also apply 😅

But overall I fully agree with @gmischler and his arguments
Thank you for taking the time to answer in details, it saved me some time to do it, and your arguments were good and clearly explained

I'm going to use my "maintainer powers" and establish that this suggestion is discarded.
However, and I want to thank you @Tolker-KU for opening this discussion, and for your will to introduce helpful tools on this project! 👍

**Comment by andersonhc** [comment]
I added isort to my Visual Studio Code setup, now it's running isort and black every time I save a file.

Thank you for the suggestion @Tolker-KU
